### ISSUE TITLE
Problem with mounting volume and buildstep

### ISSUE THREAD

**Issue by dac09** [dyson/dokku-docker-options#8]
Hi,

First off, thanks for creating the plugin.

I've been trying to use this with dokku, however, the -v option seems to interfere with the build process from buildpack. I found a similar issue here with your other plugin (that's resolved now) https://github.com/progrium/dokku/issues/906

The error I see when deploying is the same `rm: cannot remove '/app/data': Device or resource busy`. However, it works fine with the persistent storage plugin.

Thanks,
Daniel

**Comment by dyson** [comment]
Are you running the latest version?

I merged https://github.com/dyson/dokku-docker-options/pull/7 which is the same fix in persistent storage.

There is also a whole new branch https://github.com/dyson/dokku-docker-options/tree/dokku-merge you can try which provides individual settings per phase. If you wanted to give it a test that would be awesome as it's going to be merged into dokku. 

Let me know how you go.

**Comment by Benjamin-Dobell** [comment]
Same problem, dokku-merge branch resolved the issue.

Strangely enough the issue wasn't resolved though using the latest master (despite #7 clearly being merged). Ah well, soon this will all be official and it will all be magic :wink:

**Comment by Benjamin-Dobell** [comment]
F****CK!!!! Sorry. Oh man, all the persistent data directories have been wiped. Oh man, oh man, this is not good.

**Comment by Benjamin-Dobell** [comment]
Sorry for the melt-down there, guys!

Recovering from out Linode backup now. Never had to use the backup service before so hopefully everything works. Unfortunately the backup is 20 hours old, so some data will be lost. Nonetheless, __this__ is why you should aways have backups.

@dac09 I haven't really looked into the details of the issue, but any idea what caused all my mounted directories to be wiped?

__Some info about our setup__

We're running about 6 dokku apps with 10+ persistent/mounted directories hooked up to various app instances. Most directories (or directories nested in other directories) are mounted simultaneously on at least two or more dokku apps (docker instances).

I'd love to know what happened so I can ensure I don't repeat the mistake. So any pearls of wisdom you can offer would be immensely appreciated.
